version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  client:
    build: ./client
    image: client:latest
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - serverapi

  serverapi:
    build: ./api
    image: serverapi:latest
    container_name: backend
    ports:
      - 5432:5432
    links: 
      - mongodb
    depends_on:
      - mongodb

volumes: 
  mongodb: {}
