version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - host
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  client:
    build: ./client
    container_name: frontend
    restart: always
    networks:
      - host
    ports:
      - 3000:3000
    depends_on:
      - serverapi

  serverapi:
    build: ./api
    container_name: backend
    networks:
      - host
    restart: always
    ports:
      - 6868:8080
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb

networks:
  host:
    driver: bridge

volumes: 
  mongodb: 
